using ClosedXML.Excel;using System.Security.AccessControl;using System.Security.Principal;
namespace NTFSSuite;
public static class AclPatternAnalyzer
{
 public static void Run(string template,string root,int levels,string output,Action<int,string>? progress=null)
 {
  var dirs=TemplateService.ReadDirectories(template,root,levels);var patterns=new Dictionary<string,AclPattern>(StringComparer.Ordinal);var examples=new List<object[]>();int done=0;
  foreach(var d in dirs){done++;progress?.Invoke(done*100/Math.Max(1,dirs.Count),d.RelativePath);if(string.IsNullOrEmpty(d.FullPath)||!Directory.Exists(d.FullPath))continue;DirectorySecurity sec;try{sec=FileSystemAclExtensions.GetAccessControl(new DirectoryInfo(d.FullPath),AccessControlSections.Access);}catch{continue;}
   foreach(FileSystemAccessRule rule in sec.GetAccessRules(true,true,typeof(SecurityIdentifier))){var sid=(SecurityIdentifier)rule.IdentityReference;string principal;try{principal=((NTAccount)sid.Translate(typeof(NTAccount))).Value;}catch{principal=sid.Value;}string scope=Scope(rule);string rights=NormalizeRights(rule.FileSystemRights);string signature=$"{rule.AccessControlType}|{scope}|{rights}|Inherited={rule.IsInherited}";if(!patterns.TryGetValue(signature,out var p)){p=new AclPattern{Signature=signature,Type=rule.AccessControlType.ToString(),Scope=scope,Rights=rights,Suggested=Suggest(rule),ExamplePrincipal=principal,ExamplePath=d.RelativePath,ExampleInherited=rule.IsInherited};patterns.Add(signature,p);}p.Frequency++;examples.Add(new object[]{"",principal,d.RelativePath,rule.AccessControlType.ToString(),scope,rights,rule.IsInherited?"Sí":"No",Suggest(rule)});}
  }
  int index=1;foreach(var p in patterns.Values.OrderByDescending(x=>x.Frequency))p.Id="ACL"+(index++).ToString("000");var sigToId=patterns.Values.ToDictionary(x=>x.Signature,x=>x.Id);foreach(var e in examples){string signature=$"{e[3]}|{e[4]}|{e[5]}|Inherited={(string)e[6]=="Sí"}";e[0]=sigToId[signature];}
  Write(output,patterns.Values.OrderBy(x=>x.Id).ToList(),examples,dirs);
 }
 static string NormalizeRights(FileSystemRights r)=>(r&~FileSystemRights.Synchronize).ToString();
 static string Scope(FileSystemAccessRule r){if(r.InheritanceFlags==(InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit)&&r.PropagationFlags==PropagationFlags.None)return "Esta carpeta, subcarpetas y archivos";if(r.InheritanceFlags==InheritanceFlags.None)return "Solo esta carpeta";return r.InheritanceFlags+" / "+r.PropagationFlags;}
 static string Suggest(FileSystemAccessRule r){var n=r.FileSystemRights&~FileSystemRights.Synchronize;if(r.AccessControlType==AccessControlType.Allow&&n==FileSystemRights.FullControl)return "LEM";if(r.AccessControlType==AccessControlType.Allow&&(n&FileSystemRights.Modify)==FileSystemRights.Modify)return "M";if(r.AccessControlType==AccessControlType.Allow&&(n&FileSystemRights.ReadAndExecute)==FileSystemRights.ReadAndExecute)return "L";return "SIN CLASIFICAR";}
 static void Write(string output,List<AclPattern> patterns,List<object[]> examples,List<DirectoryItem> dirs){using var wb=new XLWorkbook();var s=wb.AddWorksheet("RESUMEN");Header(s,new[]{"Concepto","Cantidad"});s.Cell(2,1).Value="Directorios documentados";s.Cell(2,2).Value=dirs.Count;s.Cell(3,1).Value="Directorios resueltos";s.Cell(3,2).Value=dirs.Count(x=>x.FullPath.Length>0);s.Cell(4,1).Value="Combinaciones únicas";s.Cell(4,2).Value=patterns.Count;s.Cell(5,1).Value="Entradas ACL analizadas";s.Cell(5,2).Value=patterns.Sum(x=>x.Frequency);s.Columns().AdjustToContents();
  var c=wb.AddWorksheet("COMBINACIONES DETECTADAS");Header(c,new[]{"ID","Frecuencia","Permitir/Denegar","Se aplica a","Heredado ejemplo","Derechos avanzados","Clasificación sugerida","Usuario/Grupo ejemplo","Ruta ejemplo"});int row=2;foreach(var p in patterns){object[] v={p.Id,p.Frequency,p.Type,p.Scope,p.ExampleInherited?"Sí":"No",p.Rights,p.Suggested,p.ExamplePrincipal,p.ExamplePath};Put(c,row++,v);}c.SheetView.FreezeRows(1);c.RangeUsed().SetAutoFilter();c.Columns().AdjustToContents(12,80);
  var e=wb.AddWorksheet("EJEMPLOS");Header(e,new[]{"ID","Usuario o grupo","Ruta","Permitir/Denegar","Se aplica a","Derechos avanzados","Heredado","Clasificación sugerida"});row=2;foreach(var v in examples)Put(e,row++,v);e.SheetView.FreezeRows(1);e.RangeUsed().SetAutoFilter();e.Columns().AdjustToContents(12,80);
  var u=wb.AddWorksheet("SIN CLASIFICAR");Header(u,new[]{"ID","Frecuencia","Permitir/Denegar","Se aplica a","Derechos avanzados","Usuario/Grupo ejemplo","Ruta ejemplo"});row=2;foreach(var p in patterns.Where(x=>x.Suggested=="SIN CLASIFICAR")){object[] v={p.Id,p.Frequency,p.Type,p.Scope,p.Rights,p.ExamplePrincipal,p.ExamplePath};Put(u,row++,v);}if(u.RangeUsed()!=null)u.RangeUsed().SetAutoFilter();u.Columns().AdjustToContents(12,80);
  var r=wb.AddWorksheet("RUTAS");Header(r,new[]{"Fila","Ruta documentada","Ruta física","Estado"});row=2;foreach(var d in dirs)Put(r,row++,new object[]{d.Row,d.RelativePath,d.FullPath,d.Resolution});r.Columns().AdjustToContents(12,90);wb.SaveAs(output);}
 static void Header(IXLWorksheet s,string[] h){for(int i=0;i<h.Length;i++){var c=s.Cell(1,i+1);c.Value=h[i];c.Style.Font.Bold=true;c.Style.Font.FontColor=XLColor.White;c.Style.Fill.BackgroundColor=XLColor.FromHtml("#1F4E78");}}
 static void Put(IXLWorksheet s,int row,object[] v){for(int i=0;i<v.Length;i++)s.Cell(row,i+1).Value=XLCellValue.FromObject(v[i]);}
}